language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - mongodb
# command to run tests
script: pytest --ignore=venv/ --cov
after_sucess:
  - secure: a62Bx9d4Z1zIYdgSbRQItIHGj+VfgMjAGR/KVH6bBY/XLy254jAZTeG1tvDV88xKK/MAtb/96dGpsqu2DGGLs3hmMul1HgOIfiU+XvEUC1jJU4pKj7USizH/CW4f+tAR16GCcWF0J2SWav3emE9TsZZaPWOH2+MOi6rnWkDgmI1JGGwCPIUarf2UIIrrQhLKhB42FILN8CBFUzBHUHz14w81GEGc3Cyfjct39oLvJObjBzAme7lmdfLTmwyQk6flPgBzOC9BvIsge5ztB3RVokDpO9oge1F7LBkhO7CmtJkSOXORi/ABIxtr46wb0lPpkVnA8fHGLKQT891LuZlvBDazOfWAbyBHYLskiuhpdyi5AhCNJ4OJ0hST+b9JF+ZQARrKT3fUWOcOTQHjRICxQkgiFwRVQq8ae3iXLshPHlrTOHwMZ7OERu5tq4+zTri1gUQf5QKe9zNCNhjTg0U5mHphcyuNsimpihhaDLU5tBf7maLAv3vm5VwTUOovctmoO+XMbSuWJc0uWInEB5vPfX1Qj3XzOr2YkEKOTDbqcQGJNy4QPHXcgSxe//twXOHy8HnNJ9A3nmcM3mpTxFy8qXFSNiLe4ohSqjuSUlP8h+2cZ//nPYfEZm2hhu3YABdPHZsWiakc1Q0rybZhixywrB6QmM0VzVifg/nC5Ua0Wkc=

