language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - mongodb
# command to run tests
script: pytest --ignore=virtualenv/ --cov
addons:
    code_climate:
        repo_token:
            secure: u/vhdF8NoRNcEnANAYTXzeTLGY7xRkbZNMuSp9i2VQ9B1dkqXFSUDbQedQh20ZluiNwuBOtvzub9GROAphOg9+HGJ0nIJvfulgRZ4MyxW4SUoySpFTtbK4XIXzRT51+2ZX+7FWso6GlCNYSKeY1jOhnzG9uxAQ0kC+MMFcUHUF9XVi7puijgJZUVfdb08DIGZomluITmXt7LyebUDe7zLG+EYSz1z9Kn0MOsDLS5DkVvjOIVmC3FTdCvj8liVlPQo0FJJRKL0Q+IOTTHKv8nub1gRJm5xVyceALwDZHhB+z4vP2oPnLh5YnP9LwC3tgAuwt4/M8axFfyxJZPnFXccu/qEuGlvewjjGTOLsE6A/lusdc/eJOXSuaagP0rTE3fDfyt0wbgVEKgxWg3xnd+5U3893zqjV0/X/wwfN8adn9DaMP2NwDraiHm5F1w7S1K4SoilmvWElsnfMu5NUBb2uZdJ2nIupYCl0MD/d/Dz6DCzzHvgkgvOCWNYP8MlYcP0xYL15TAgEVDldgJqwZLYl5Xd3QgU3xSBKG2SWkY4Q6iJsUmF/wAoXZgXWHARm50q+JCyc77orW7HSAoOd5ttLMeYQtr/Do1GQNCkU/28kwREWz4G/ugs9rPgY+BqhV3woxHnqqQ0LD1y/xyjLfoaO1wQifUzKxnKVFZfEfu1RY=

