language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - mongodb
# command to run tests
script: pytest --ignore=venv/
addons:
    code_climate:
        repo_token: 76ae3266082ccc738fa128fb381ef2e12fe153de820e85a623138a89f959d720

